version: 1.0.{build}
branches:
 only:
   - master
pull_requests:
 do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /(Created|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
environment:
  SONAR_TOKEN: 
    secure: Ygi3OANCoY8kUyJ7TJ9ewyqEkNxw6o9MZkPWOZfLCH/Dsss8df3yGsL0tMVB1abz
dotnet_csproj: 
  patch: true 
  file: '**\*.csproj' 
  version: '1.0.{build}' 
  package_version: '1.0.{build}' 
  assembly_version: '1.0.{build}'
  file_version: '1.0.{build}'
  informational_version: '1.0.{build}'
before_build:
- cmd: nuget restore
- cmd: choco install opencover.portable
- cmd: choco install codecov
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
build_script:
 - dotnet tool install --global dotnet-sonarscanner
 - dotnet sonarscanner begin /k:"guibranco_CrispyWaffle" /d:sonar.organization="guibranco-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%" /v:"%APPVEYOR_BUILD_NUMBER%" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.coverage.exclusions="CrispyWaffle.Tests/**,**/*Tests.cs" /d:sonar.cs.opencover.reportsPaths="%CD%\CrispyWaffle.Tests\coverage.opencover.xml"
 - dotnet build
 - ps: dotnet test .\CrispyWaffle.Tests\CrispyWaffle.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
 - dotnet sonarscanner end /d:sonar.login="%SONAR_TOKEN%"
 - codecov -f "CrispyWaffle.Tests\coverage.opencover.xml"
after_build:
- xcopy %CD%\CrispyWaffle\bin\Release\netstandard2.0\*.* %CD%\src\
- copy %CD%\CrispyWaffle\bin\Release\CrispyWaffle.1.0.%APPVEYOR_BUILD_NUMBER%.nupkg CrispyWaffle.%APPVEYOR_BUILD_VERSION%.nupkg
- rd /s /q %CD%\CrispyWaffle\bin\Release\
- cd %CD%
- 7z a -tzip -mx9 "CrispyWaffle.v%APPVEYOR_BUILD_VERSION%.zip" src
artifacts:
- path: CrispyWaffle.v%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile
- path: CrispyWaffle.%APPVEYOR_BUILD_VERSION%.nupkg
  name: Package
deploy:
- provider: Environment
  name: NuGet
  artifact: Package
- provider: GitHub
  tag: $(appveyor_build_version)
  auth_token:
    secure: VgYYJdvNLy/n9/uxxlaF0bMpIIrVxCb+dGr66U9nWfPWSN2ySdfuilO8klAw0uvF
  force_update: true
  artifact: ZipFile