site_name: Crispy Waffle
repo_url: https://github.com/guibranco/crispywaffle
extra_css:
  - extra.css
theme:
  name: readthedocs
  logo: logo.png
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github
plugins:
  - git-authors
  - git-committers:
      repository: guibranco/CrispyWaffle
      branch: main
